#pragma once
#include <array>
#include <string>

#include "../../types.hpp"

namespace bemu::gb {
struct OpcodeMetadata {
    std::string mnemonic;
    u8 length;
    u8 dots;
    u8 dots_branched;
    std::string flags;
};

// Extracted from https://gbdev.io/gb-opcodes/optables/#standard
constexpr static std::array opcodes = {OpcodeMetadata{"NOP", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD BC, n16", 3, 12, 12, "- - - -"},
                                       OpcodeMetadata{"LD [BC], A", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"INC BC", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"INC B", 1, 4, 4, "Z 0 H -"},
                                       OpcodeMetadata{"DEC B", 1, 4, 4, "Z 1 H -"},
                                       OpcodeMetadata{"LD B, n8", 2, 8, 8, "- - - -"},
                                       OpcodeMetadata{"RLCA", 1, 4, 4, "0 0 0 C"},
                                       OpcodeMetadata{"LD [a16], SP", 3, 20, 20, "- - - -"},
                                       OpcodeMetadata{"ADD HL, BC", 1, 8, 8, "- 0 H C"},
                                       OpcodeMetadata{"LD A, [BC]", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"DEC BC", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"INC C", 1, 4, 4, "Z 0 H -"},
                                       OpcodeMetadata{"DEC C", 1, 4, 4, "Z 1 H -"},
                                       OpcodeMetadata{"LD C, n8", 2, 8, 8, "- - - -"},
                                       OpcodeMetadata{"RRCA", 1, 4, 4, "0 0 0 C"},
                                       OpcodeMetadata{"STOP n8", 2, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD DE, n16", 3, 12, 12, "- - - -"},
                                       OpcodeMetadata{"LD [DE], A", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"INC DE", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"INC D", 1, 4, 4, "Z 0 H -"},
                                       OpcodeMetadata{"DEC D", 1, 4, 4, "Z 1 H -"},
                                       OpcodeMetadata{"LD D, n8", 2, 8, 8, "- - - -"},
                                       OpcodeMetadata{"RLA", 1, 4, 4, "0 0 0 C"},
                                       OpcodeMetadata{"JR e8", 2, 12, 12, "- - - -"},
                                       OpcodeMetadata{"ADD HL, DE", 1, 8, 8, "- 0 H C"},
                                       OpcodeMetadata{"LD A, [DE]", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"DEC DE", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"INC E", 1, 4, 4, "Z 0 H -"},
                                       OpcodeMetadata{"DEC E", 1, 4, 4, "Z 1 H -"},
                                       OpcodeMetadata{"LD E, n8", 2, 8, 8, "- - - -"},
                                       OpcodeMetadata{"RRA", 1, 4, 4, "0 0 0 C"},
                                       OpcodeMetadata{"JR NZ, e8", 2, 8, 12, "- - - -"},
                                       OpcodeMetadata{"LD HL, n16", 3, 12, 12, "- - - -"},
                                       OpcodeMetadata{"LD [HL+], A", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"INC HL", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"INC H", 1, 4, 4, "Z 0 H -"},
                                       OpcodeMetadata{"DEC H", 1, 4, 4, "Z 1 H -"},
                                       OpcodeMetadata{"LD H, n8", 2, 8, 8, "- - - -"},
                                       OpcodeMetadata{"DAA", 1, 4, 4, "Z - 0 C"},
                                       OpcodeMetadata{"JR Z, e8", 2, 8, 12, "- - - -"},
                                       OpcodeMetadata{"ADD HL, HL", 1, 8, 8, "- 0 H C"},
                                       OpcodeMetadata{"LD A, [HL+]", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"DEC HL", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"INC L", 1, 4, 4, "Z 0 H -"},
                                       OpcodeMetadata{"DEC L", 1, 4, 4, "Z 1 H -"},
                                       OpcodeMetadata{"LD L, n8", 2, 8, 8, "- - - -"},
                                       OpcodeMetadata{"CPL", 1, 4, 4, "- 1 1 -"},
                                       OpcodeMetadata{"JR NC, e8", 2, 8, 12, "- - - -"},
                                       OpcodeMetadata{"LD SP, n16", 3, 12, 12, "- - - -"},
                                       OpcodeMetadata{"LD [HL-], A", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"INC SP", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"INC [HL]", 1, 12, 12, "Z 0 H -"},
                                       OpcodeMetadata{"DEC [HL]", 1, 12, 12, "Z 1 H -"},
                                       OpcodeMetadata{"LD [HL], n8", 2, 12, 12, "- - - -"},
                                       OpcodeMetadata{"SCF", 1, 4, 4, "- 0 0 1"},
                                       OpcodeMetadata{"JR C, e8", 2, 8, 12, "- - - -"},
                                       OpcodeMetadata{"ADD HL, SP", 1, 8, 8, "- 0 H C"},
                                       OpcodeMetadata{"LD A, [HL-]", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"DEC SP", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"INC A", 1, 4, 4, "Z 0 H -"},
                                       OpcodeMetadata{"DEC A", 1, 4, 4, "Z 1 H -"},
                                       OpcodeMetadata{"LD A, n8", 2, 8, 8, "- - - -"},
                                       OpcodeMetadata{"CCF", 1, 4, 4, "- 0 0 C"},
                                       OpcodeMetadata{"LD B, B", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD B, C", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD B, D", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD B, E", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD B, H", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD B, L", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD B, [HL]", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"LD B, A", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD C, B", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD C, C", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD C, D", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD C, E", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD C, H", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD C, L", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD C, [HL]", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"LD C, A", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD D, B", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD D, C", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD D, D", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD D, E", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD D, H", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD D, L", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD D, [HL]", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"LD D, A", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD E, B", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD E, C", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD E, D", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD E, E", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD E, H", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD E, L", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD E, [HL]", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"LD E, A", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD H, B", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD H, C", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD H, D", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD H, E", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD H, H", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD H, L", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD H, [HL]", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"LD H, A", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD L, B", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD L, C", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD L, D", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD L, E", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD L, H", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD L, L", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD L, [HL]", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"LD L, A", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD [HL], B", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"LD [HL], C", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"LD [HL], D", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"LD [HL], E", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"LD [HL], H", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"LD [HL], L", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"HALT", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD [HL], A", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"LD A, B", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD A, C", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD A, D", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD A, E", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD A, H", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD A, L", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD A, [HL]", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"LD A, A", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"ADD A, B", 1, 4, 4, "Z 0 H C"},
                                       OpcodeMetadata{"ADD A, C", 1, 4, 4, "Z 0 H C"},
                                       OpcodeMetadata{"ADD A, D", 1, 4, 4, "Z 0 H C"},
                                       OpcodeMetadata{"ADD A, E", 1, 4, 4, "Z 0 H C"},
                                       OpcodeMetadata{"ADD A, H", 1, 4, 4, "Z 0 H C"},
                                       OpcodeMetadata{"ADD A, L", 1, 4, 4, "Z 0 H C"},
                                       OpcodeMetadata{"ADD A, [HL]", 1, 8, 8, "Z 0 H C"},
                                       OpcodeMetadata{"ADD A, A", 1, 4, 4, "Z 0 H C"},
                                       OpcodeMetadata{"ADC A, B", 1, 4, 4, "Z 0 H C"},
                                       OpcodeMetadata{"ADC A, C", 1, 4, 4, "Z 0 H C"},
                                       OpcodeMetadata{"ADC A, D", 1, 4, 4, "Z 0 H C"},
                                       OpcodeMetadata{"ADC A, E", 1, 4, 4, "Z 0 H C"},
                                       OpcodeMetadata{"ADC A, H", 1, 4, 4, "Z 0 H C"},
                                       OpcodeMetadata{"ADC A, L", 1, 4, 4, "Z 0 H C"},
                                       OpcodeMetadata{"ADC A, [HL]", 1, 8, 8, "Z 0 H C"},
                                       OpcodeMetadata{"ADC A, A", 1, 4, 4, "Z 0 H C"},
                                       OpcodeMetadata{"SUB A, B", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"SUB A, C", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"SUB A, D", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"SUB A, E", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"SUB A, H", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"SUB A, L", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"SUB A, [HL]", 1, 8, 8, "Z 1 H C"},
                                       OpcodeMetadata{"SUB A, A", 1, 4, 4, "1 1 0 0"},
                                       OpcodeMetadata{"SBC A, B", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"SBC A, C", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"SBC A, D", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"SBC A, E", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"SBC A, H", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"SBC A, L", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"SBC A, [HL]", 1, 8, 8, "Z 1 H C"},
                                       OpcodeMetadata{"SBC A, A", 1, 4, 4, "Z 1 H -"},
                                       OpcodeMetadata{"AND A, B", 1, 4, 4, "Z 0 1 0"},
                                       OpcodeMetadata{"AND A, C", 1, 4, 4, "Z 0 1 0"},
                                       OpcodeMetadata{"AND A, D", 1, 4, 4, "Z 0 1 0"},
                                       OpcodeMetadata{"AND A, E", 1, 4, 4, "Z 0 1 0"},
                                       OpcodeMetadata{"AND A, H", 1, 4, 4, "Z 0 1 0"},
                                       OpcodeMetadata{"AND A, L", 1, 4, 4, "Z 0 1 0"},
                                       OpcodeMetadata{"AND A, [HL]", 1, 8, 8, "Z 0 1 0"},
                                       OpcodeMetadata{"AND A, A", 1, 4, 4, "Z 0 1 0"},
                                       OpcodeMetadata{"XOR A, B", 1, 4, 4, "Z 0 0 0"},
                                       OpcodeMetadata{"XOR A, C", 1, 4, 4, "Z 0 0 0"},
                                       OpcodeMetadata{"XOR A, D", 1, 4, 4, "Z 0 0 0"},
                                       OpcodeMetadata{"XOR A, E", 1, 4, 4, "Z 0 0 0"},
                                       OpcodeMetadata{"XOR A, H", 1, 4, 4, "Z 0 0 0"},
                                       OpcodeMetadata{"XOR A, L", 1, 4, 4, "Z 0 0 0"},
                                       OpcodeMetadata{"XOR A, [HL]", 1, 8, 8, "Z 0 0 0"},
                                       OpcodeMetadata{"XOR A, A", 1, 4, 4, "1 0 0 0"},
                                       OpcodeMetadata{"OR A, B", 1, 4, 4, "Z 0 0 0"},
                                       OpcodeMetadata{"OR A, C", 1, 4, 4, "Z 0 0 0"},
                                       OpcodeMetadata{"OR A, D", 1, 4, 4, "Z 0 0 0"},
                                       OpcodeMetadata{"OR A, E", 1, 4, 4, "Z 0 0 0"},
                                       OpcodeMetadata{"OR A, H", 1, 4, 4, "Z 0 0 0"},
                                       OpcodeMetadata{"OR A, L", 1, 4, 4, "Z 0 0 0"},
                                       OpcodeMetadata{"OR A, [HL]", 1, 8, 8, "Z 0 0 0"},
                                       OpcodeMetadata{"OR A, A", 1, 4, 4, "Z 0 0 0"},
                                       OpcodeMetadata{"CP A, B", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"CP A, C", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"CP A, D", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"CP A, E", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"CP A, H", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"CP A, L", 1, 4, 4, "Z 1 H C"},
                                       OpcodeMetadata{"CP A, [HL]", 1, 8, 8, "Z 1 H C"},
                                       OpcodeMetadata{"CP A, A", 1, 4, 4, "1 1 0 0"},
                                       OpcodeMetadata{"RET NZ", 1, 8, 20, "- - - -"},
                                       OpcodeMetadata{"POP BC", 1, 12, 12, "- - - -"},
                                       OpcodeMetadata{"JP NZ, a16", 3, 12, 16, "- - - -"},
                                       OpcodeMetadata{"JP a16", 3, 16, 16, "- - - -"},
                                       OpcodeMetadata{"CALL NZ, a16", 3, 12, 24, "- - - -"},
                                       OpcodeMetadata{"PUSH BC", 1, 16, 16, "- - - -"},
                                       OpcodeMetadata{"ADD A, n8", 2, 8, 8, "Z 0 H C"},
                                       OpcodeMetadata{"RST $00", 1, 16, 16, "- - - -"},
                                       OpcodeMetadata{"RET Z", 1, 8, 20, "- - - -"},
                                       OpcodeMetadata{"RET", 1, 16, 16, "- - - -"},
                                       OpcodeMetadata{"JP Z, a16", 3, 12, 16, "- - - -"},
                                       OpcodeMetadata{"PREFIX", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"CALL Z, a16", 3, 12, 24, "- - - -"},
                                       OpcodeMetadata{"CALL a16", 3, 24, 24, "- - - -"},
                                       OpcodeMetadata{"ADC A, n8", 2, 8, 8, "Z 0 H C"},
                                       OpcodeMetadata{"RST $08", 1, 16, 16, "- - - -"},
                                       OpcodeMetadata{"RET NC", 1, 8, 20, "- - - -"},
                                       OpcodeMetadata{"POP DE", 1, 12, 12, "- - - -"},
                                       OpcodeMetadata{"JP NC, a16", 3, 12, 16, "- - - -"},
                                       OpcodeMetadata{"", 0, 0, 0, ""},
                                       OpcodeMetadata{"CALL NC, a16", 3, 12, 24, "- - - -"},
                                       OpcodeMetadata{"PUSH DE", 1, 16, 16, "- - - -"},
                                       OpcodeMetadata{"SUB A, n8", 2, 8, 8, "Z 1 H C"},
                                       OpcodeMetadata{"RST $10", 1, 16, 16, "- - - -"},
                                       OpcodeMetadata{"RET C", 1, 8, 20, "- - - -"},
                                       OpcodeMetadata{"RETI", 1, 16, 16, "- - - -"},
                                       OpcodeMetadata{"JP C, a16", 3, 12, 16, "- - - -"},
                                       OpcodeMetadata{"", 0, 0, 0, ""},
                                       OpcodeMetadata{"CALL C, a16", 3, 12, 24, "- - - -"},
                                       OpcodeMetadata{"", 0, 0, 0, ""},
                                       OpcodeMetadata{"SBC A, n8", 2, 8, 8, "Z 1 H C"},
                                       OpcodeMetadata{"RST $18", 1, 16, 16, "- - - -"},
                                       OpcodeMetadata{"LDH [a8], A", 2, 12, 12, "- - - -"},
                                       OpcodeMetadata{"POP HL", 1, 12, 12, "- - - -"},
                                       OpcodeMetadata{"LDH [C], A", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"", 0, 0, 0, ""},
                                       OpcodeMetadata{"", 0, 0, 0, ""},
                                       OpcodeMetadata{"PUSH HL", 1, 16, 16, "- - - -"},
                                       OpcodeMetadata{"AND A, n8", 2, 8, 8, "Z 0 1 0"},
                                       OpcodeMetadata{"RST $20", 1, 16, 16, "- - - -"},
                                       OpcodeMetadata{"ADD SP, e8", 2, 16, 16, "0 0 H C"},
                                       OpcodeMetadata{"JP HL", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"LD [a16], A", 3, 16, 16, "- - - -"},
                                       OpcodeMetadata{"", 0, 0, 0, ""},
                                       OpcodeMetadata{"", 0, 0, 0, ""},
                                       OpcodeMetadata{"", 0, 0, 0, ""},
                                       OpcodeMetadata{"XOR A, n8", 2, 8, 8, "Z 0 0 0"},
                                       OpcodeMetadata{"RST $28", 1, 16, 16, "- - - -"},
                                       OpcodeMetadata{"LDH A, [a8]", 2, 12, 12, "- - - -"},
                                       OpcodeMetadata{"POP AF", 1, 12, 12, "Z N H C"},
                                       OpcodeMetadata{"LDH A, [C]", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"DI", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"", 0, 0, 0, ""},
                                       OpcodeMetadata{"PUSH AF", 1, 16, 16, "- - - -"},
                                       OpcodeMetadata{"OR A, n8", 2, 8, 8, "Z 0 0 0"},
                                       OpcodeMetadata{"RST $30", 1, 16, 16, "- - - -"},
                                       OpcodeMetadata{"LD HL, SP + e8", 2, 12, 12, "0 0 H C"},
                                       OpcodeMetadata{"LD SP, HL", 1, 8, 8, "- - - -"},
                                       OpcodeMetadata{"LD A, [a16]", 3, 16, 16, "- - - -"},
                                       OpcodeMetadata{"EI", 1, 4, 4, "- - - -"},
                                       OpcodeMetadata{"", 0, 0, 0, ""},
                                       OpcodeMetadata{"", 0, 0, 0, ""},
                                       OpcodeMetadata{"CP A, n8", 2, 8, 8, "Z 1 H C"},
                                       OpcodeMetadata{"RST $38", 1, 16, 16, "- - - -"}};

// Extracted from https://gbdev.io/gb-opcodes/optables/#prefixed
constexpr static std::array opcodes_cb = {
    OpcodeMetadata{"RLC B", 2, 8, 8, "Z 0 0 C"},         OpcodeMetadata{"RLC C", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"RLC D", 2, 8, 8, "Z 0 0 C"},         OpcodeMetadata{"RLC E", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"RLC H", 2, 8, 8, "Z 0 0 C"},         OpcodeMetadata{"RLC L", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"RLC [HL]", 2, 16, 16, "Z 0 0 C"},    OpcodeMetadata{"RLC A", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"RRC B", 2, 8, 8, "Z 0 0 C"},         OpcodeMetadata{"RRC C", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"RRC D", 2, 8, 8, "Z 0 0 C"},         OpcodeMetadata{"RRC E", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"RRC H", 2, 8, 8, "Z 0 0 C"},         OpcodeMetadata{"RRC L", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"RRC [HL]", 2, 16, 16, "Z 0 0 C"},    OpcodeMetadata{"RRC A", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"RL B", 2, 8, 8, "Z 0 0 C"},          OpcodeMetadata{"RL C", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"RL D", 2, 8, 8, "Z 0 0 C"},          OpcodeMetadata{"RL E", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"RL H", 2, 8, 8, "Z 0 0 C"},          OpcodeMetadata{"RL L", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"RL [HL]", 2, 16, 16, "Z 0 0 C"},     OpcodeMetadata{"RL A", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"RR B", 2, 8, 8, "Z 0 0 C"},          OpcodeMetadata{"RR C", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"RR D", 2, 8, 8, "Z 0 0 C"},          OpcodeMetadata{"RR E", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"RR H", 2, 8, 8, "Z 0 0 C"},          OpcodeMetadata{"RR L", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"RR [HL]", 2, 16, 16, "Z 0 0 C"},     OpcodeMetadata{"RR A", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"SLA B", 2, 8, 8, "Z 0 0 C"},         OpcodeMetadata{"SLA C", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"SLA D", 2, 8, 8, "Z 0 0 C"},         OpcodeMetadata{"SLA E", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"SLA H", 2, 8, 8, "Z 0 0 C"},         OpcodeMetadata{"SLA L", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"SLA [HL]", 2, 16, 16, "Z 0 0 C"},    OpcodeMetadata{"SLA A", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"SRA B", 2, 8, 8, "Z 0 0 C"},         OpcodeMetadata{"SRA C", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"SRA D", 2, 8, 8, "Z 0 0 C"},         OpcodeMetadata{"SRA E", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"SRA H", 2, 8, 8, "Z 0 0 C"},         OpcodeMetadata{"SRA L", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"SRA [HL]", 2, 16, 16, "Z 0 0 C"},    OpcodeMetadata{"SRA A", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"SWAP B", 2, 8, 8, "Z 0 0 0"},        OpcodeMetadata{"SWAP C", 2, 8, 8, "Z 0 0 0"},
    OpcodeMetadata{"SWAP D", 2, 8, 8, "Z 0 0 0"},        OpcodeMetadata{"SWAP E", 2, 8, 8, "Z 0 0 0"},
    OpcodeMetadata{"SWAP H", 2, 8, 8, "Z 0 0 0"},        OpcodeMetadata{"SWAP L", 2, 8, 8, "Z 0 0 0"},
    OpcodeMetadata{"SWAP [HL]", 2, 16, 16, "Z 0 0 0"},   OpcodeMetadata{"SWAP A", 2, 8, 8, "Z 0 0 0"},
    OpcodeMetadata{"SRL B", 2, 8, 8, "Z 0 0 C"},         OpcodeMetadata{"SRL C", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"SRL D", 2, 8, 8, "Z 0 0 C"},         OpcodeMetadata{"SRL E", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"SRL H", 2, 8, 8, "Z 0 0 C"},         OpcodeMetadata{"SRL L", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"SRL [HL]", 2, 16, 16, "Z 0 0 C"},    OpcodeMetadata{"SRL A", 2, 8, 8, "Z 0 0 C"},
    OpcodeMetadata{"BIT 0, B", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 0, C", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 0, D", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 0, E", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 0, H", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 0, L", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 0, [HL]", 2, 12, 12, "Z 0 1 -"}, OpcodeMetadata{"BIT 0, A", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 1, B", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 1, C", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 1, D", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 1, E", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 1, H", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 1, L", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 1, [HL]", 2, 12, 12, "Z 0 1 -"}, OpcodeMetadata{"BIT 1, A", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 2, B", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 2, C", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 2, D", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 2, E", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 2, H", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 2, L", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 2, [HL]", 2, 12, 12, "Z 0 1 -"}, OpcodeMetadata{"BIT 2, A", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 3, B", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 3, C", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 3, D", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 3, E", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 3, H", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 3, L", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 3, [HL]", 2, 12, 12, "Z 0 1 -"}, OpcodeMetadata{"BIT 3, A", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 4, B", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 4, C", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 4, D", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 4, E", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 4, H", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 4, L", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 4, [HL]", 2, 12, 12, "Z 0 1 -"}, OpcodeMetadata{"BIT 4, A", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 5, B", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 5, C", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 5, D", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 5, E", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 5, H", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 5, L", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 5, [HL]", 2, 12, 12, "Z 0 1 -"}, OpcodeMetadata{"BIT 5, A", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 6, B", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 6, C", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 6, D", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 6, E", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 6, H", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 6, L", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 6, [HL]", 2, 12, 12, "Z 0 1 -"}, OpcodeMetadata{"BIT 6, A", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 7, B", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 7, C", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 7, D", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 7, E", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 7, H", 2, 8, 8, "Z 0 1 -"},      OpcodeMetadata{"BIT 7, L", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"BIT 7, [HL]", 2, 12, 12, "Z 0 1 -"}, OpcodeMetadata{"BIT 7, A", 2, 8, 8, "Z 0 1 -"},
    OpcodeMetadata{"RES 0, B", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 0, C", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 0, D", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 0, E", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 0, H", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 0, L", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 0, [HL]", 2, 16, 16, "- - - -"}, OpcodeMetadata{"RES 0, A", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 1, B", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 1, C", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 1, D", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 1, E", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 1, H", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 1, L", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 1, [HL]", 2, 16, 16, "- - - -"}, OpcodeMetadata{"RES 1, A", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 2, B", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 2, C", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 2, D", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 2, E", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 2, H", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 2, L", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 2, [HL]", 2, 16, 16, "- - - -"}, OpcodeMetadata{"RES 2, A", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 3, B", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 3, C", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 3, D", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 3, E", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 3, H", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 3, L", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 3, [HL]", 2, 16, 16, "- - - -"}, OpcodeMetadata{"RES 3, A", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 4, B", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 4, C", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 4, D", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 4, E", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 4, H", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 4, L", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 4, [HL]", 2, 16, 16, "- - - -"}, OpcodeMetadata{"RES 4, A", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 5, B", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 5, C", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 5, D", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 5, E", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 5, H", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 5, L", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 5, [HL]", 2, 16, 16, "- - - -"}, OpcodeMetadata{"RES 5, A", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 6, B", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 6, C", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 6, D", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 6, E", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 6, H", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 6, L", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 6, [HL]", 2, 16, 16, "- - - -"}, OpcodeMetadata{"RES 6, A", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 7, B", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 7, C", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 7, D", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 7, E", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 7, H", 2, 8, 8, "- - - -"},      OpcodeMetadata{"RES 7, L", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"RES 7, [HL]", 2, 16, 16, "- - - -"}, OpcodeMetadata{"RES 7, A", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 0, B", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 0, C", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 0, D", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 0, E", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 0, H", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 0, L", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 0, [HL]", 2, 16, 16, "- - - -"}, OpcodeMetadata{"SET 0, A", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 1, B", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 1, C", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 1, D", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 1, E", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 1, H", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 1, L", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 1, [HL]", 2, 16, 16, "- - - -"}, OpcodeMetadata{"SET 1, A", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 2, B", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 2, C", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 2, D", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 2, E", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 2, H", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 2, L", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 2, [HL]", 2, 16, 16, "- - - -"}, OpcodeMetadata{"SET 2, A", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 3, B", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 3, C", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 3, D", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 3, E", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 3, H", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 3, L", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 3, [HL]", 2, 16, 16, "- - - -"}, OpcodeMetadata{"SET 3, A", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 4, B", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 4, C", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 4, D", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 4, E", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 4, H", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 4, L", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 4, [HL]", 2, 16, 16, "- - - -"}, OpcodeMetadata{"SET 4, A", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 5, B", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 5, C", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 5, D", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 5, E", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 5, H", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 5, L", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 5, [HL]", 2, 16, 16, "- - - -"}, OpcodeMetadata{"SET 5, A", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 6, B", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 6, C", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 6, D", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 6, E", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 6, H", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 6, L", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 6, [HL]", 2, 16, 16, "- - - -"}, OpcodeMetadata{"SET 6, A", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 7, B", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 7, C", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 7, D", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 7, E", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 7, H", 2, 8, 8, "- - - -"},      OpcodeMetadata{"SET 7, L", 2, 8, 8, "- - - -"},
    OpcodeMetadata{"SET 7, [HL]", 2, 16, 16, "- - - -"}, OpcodeMetadata{"SET 7, A", 2, 8, 8, "- - - -"}};
}  // namespace bemu::gb